#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="JetBrainsMono Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=16                    # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
# launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
	height=30
	color=${ALPHA_BAR}${BASE}
	position=bottom
	sticky=on
	padding_right=0
	padding_left=0
	y_offset=5
	margin=10
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
	updates=when_shown
	icon.font="$FONT:Bold:16.0"
	icon.color=${ALPHA_ITEM}${TEXT}
	icon.padding_left=$PADDINGS
	icon.padding_right=$PADDINGS

	label.font="$FONT:Semibold:14.0"
	label.color=${ALPHA_ITEM}${TEXT}
	label.padding_left=$PADDINGS
	label.padding_right=$PADDINGS

	background.height=30
	background.corner_radius=10
	background.border_color=0x7f${SUBTEXT0}
	background.border_width=2

	popup.background.border_width=2
	popup.background.corner_radius=10
	popup.background.border_color=0x7f${SUBTEXT0}
	popup.background.color=$POPUP_BACKGROUND_COLOR
	popup.background.shadow.drawing=on
	popup.blur_radius=20

	shadow=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/spaces.sh"

source "$ITEM_DIR/front_app.sh"

spaces=(
	background.color=${ALPHA_ITEM}${BASE}
)

sketchybar --add bracket spaces '/space\..*/' front_app \
	--set spaces "${spaces[@]}"

# Right
source "$ITEM_DIR/calendar.sh"

source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"

status_bracket=(
 background.color=${ALPHA_ITEM}${BASE}
)

sketchybar --add bracket status brew battery volume\
           --set status "${status_bracket[@]}"

source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update